import type { Settings, TokenColor } from '../types';
import { currentSettings } from './settings';
import { data, findFont } from '../data';
import { state } from '../state';

// Configuration export templates
interface ConfigFile {
    filename: string;
    content: string;
}

/** The style of one kind of syntax token: the scheme color, plus the font choices of its role. */
interface TokenStyle {
    color: string;
    bold: boolean;
    italic: boolean;
    /** Set when the role uses a different font than the main font */
    font?: string;
    weight?: number;
}

const TOKEN_KEYS = ['comment', 'string', 'keyword', 'function', 'literal', 'variable', 'type', 'operator'] as const;
type TokenKey = typeof TOKEN_KEYS[number];

const ROLE_BY_TOKEN: Record<TokenKey, string> = {
    comment: 'comments', string: 'strings', keyword: 'keywords', function: 'function',
    literal: 'literals', variable: 'variable', type: 'type', operator: 'operator',
};

/** The names that a font has when it is installed. Generated by scripts/font-names.ts. */
interface FontNames {
    /** Per font width: the family name that selects the faces of that width */
    families: Record<string, string>;
    /** Per face ("weight:style:width"): the PostScript name */
    ps: Record<string, string>;
}

// Loaded by downloadConfig, because only the exports need it
let fontNames: Record<string, FontNames> = {};

/** The first family of a CSS font stack, without quotes. */
export function primaryFontName(font: string): string {
    return font.split(',')[0].replace(/["']/g, '').trim();
}

/** The family name of the installed font. Each width of a font has a family name of its own. */
function installedFamily(font: string, width = 'normal'): string {
    const families = fontNames[font]?.families;
    return families?.[width] ?? families?.normal ?? font;
}

/** The family name of the main font at the chosen width. */
function mainFamily(settings: Settings): string {
    return installedFamily(primaryFontName(settings.font), settings.fontWidth);
}

/** True when the installed font has a family name of its own for the chosen width. */
function hasWidthFamily(settings: Settings): boolean {
    return !!fontNames[primaryFontName(settings.font)]?.families[settings.fontWidth];
}

/** The PostScript name of the main face, which macOS apps use. Undefined when the database has no name. */
function postscriptName(settings: Settings): string | undefined {
    const ps = fontNames[primaryFontName(settings.font)]?.ps;
    const weight = Math.min(900, Math.max(100, Math.round(settings.weight / 100) * 100));
    return ps?.[`${weight}:normal:${settings.fontWidth || 'normal'}`] ?? ps?.[`${weight}:normal:normal`];
}

/** The usual form of a PostScript name, for a font that the database has no names for. */
function guessedPostscriptName(settings: Settings): string {
    const weight = weightNames(settings.weight).pango.replace('-', '') || 'Regular';
    return `${mainFamily(settings).replace(/[^A-Za-z0-9]/g, '')}-${weight}`;
}

/** The CSS font list of the main font: the name of the width first, then the names of the family. */
function cssFontList(settings: Settings, quote: string): string {
    const name = primaryFontName(settings.font);
    const names = [mainFamily(settings)];
    // On macOS, Chromium finds a face of another width only by its PostScript name
    if (hasWidthFamily(settings) && settings.fontWidth !== 'normal') names.push(postscriptName(settings) ?? name);
    names.push(installedFamily(name), name);
    return [...new Set(names)].map(n => `${quote}${n}${quote}`).join(', ') + ', monospace';
}

/** The width of one character as a fraction of the font size. */
function charWidthRatio(settings: Settings): number {
    const widths = data.fontMetrics[primaryFontName(settings.font)]?.avgCharWidth?.['16'];
    const width = widths?.[settings.fontWidth] ?? widths?.normal;
    return width ? width / 16 : 0.6;
}

/** The letter spacing as a multiple of the character width: 1 is no extra spacing. */
function cellWidthScale(settings: Settings): number {
    return Number((1 + (settings.letterSpacing || 0) / (charWidthRatio(settings) * settings.size)).toFixed(3));
}

function tokenStyles(settings: Settings): Record<TokenKey, TokenStyle> {
    const scheme = state.engine.winners.colorScheme as Record<string, TokenColor | undefined> | null | undefined;
    const mainFont = primaryFontName(settings.font);
    const styles = {} as Record<TokenKey, TokenStyle>;
    for (const key of TOKEN_KEYS) {
        const token = scheme?.[key];
        const flags = typeof token === 'object' ? token : {};
        const style: TokenStyle = { color: settings.colorScheme[key], bold: !!flags.bold, italic: !!flags.italic };
        const role = settings.roles?.[ROLE_BY_TOKEN[key]];
        if (role) {
            if (role.weight) {
                style.weight = role.weight;
                style.bold = role.weight >= 600;
            }
            if (role.style) style.italic = role.style === 'italic';
            const roleFont = role.font && primaryFontName(role.font);
            if (roleFont && roleFont !== mainFont) style.font = installedFamily(roleFont);
        }
        styles[key] = style;
    }
    return styles;
}


// Size and spacing conversions

// The app measures the font size in CSS pixels. Most desktop apps take points.
// On Windows and Linux one point is 4/3 pixel. On macOS a point is one CSS pixel.
const IS_MAC = /Mac/i.test(navigator.platform);

function toPoints(px: number, mac = false): number {
    return mac ? px : Number((px * 0.75).toFixed(2));
}

// The app's line height is a multiple of the font size. Many editors add space to
// the font's own line height instead, which is about 1.2 times the font size.
const NATURAL_LINE_HEIGHT = 1.2;

function extraLinePixels(settings: Settings): number {
    return Math.max(0, Math.round((settings.lineHeight - NATURAL_LINE_HEIGHT) * settings.size));
}

function lineHeightScale(settings: Settings): number {
    return Number(Math.max(1, settings.lineHeight / NATURAL_LINE_HEIGHT).toFixed(2));
}

const WEIGHT_NAMES: Record<number, { pango: string; emacs: string; terminal: string }> = {
    100: { pango: 'Thin', emacs: 'thin', terminal: 'thin' },
    200: { pango: 'Extra-Light', emacs: 'extra-light', terminal: 'extra-light' },
    300: { pango: 'Light', emacs: 'light', terminal: 'light' },
    400: { pango: '', emacs: 'normal', terminal: 'normal' },
    500: { pango: 'Medium', emacs: 'medium', terminal: 'medium' },
    600: { pango: 'Semi-Bold', emacs: 'semi-bold', terminal: 'semi-bold' },
    700: { pango: 'Bold', emacs: 'bold', terminal: 'bold' },
    800: { pango: 'Extra-Bold', emacs: 'extra-bold', terminal: 'extra-bold' },
    900: { pango: 'Black', emacs: 'black', terminal: 'black' },
};

function weightNames(weight: number) {
    return WEIGHT_NAMES[Math.min(900, Math.max(100, Math.round(weight / 100) * 100))];
}

const PANGO_WIDTHS: Record<string, string> = {
    'ultra-condensed': 'Ultra-Condensed', 'extra-condensed': 'Extra-Condensed', 'condensed': 'Condensed',
    'semi-condensed': 'Semi-Condensed', 'semi-expanded': 'Semi-Expanded', 'semi-wide': 'Semi-Expanded',
    'expanded': 'Expanded', 'wide': 'Expanded', 'extra-expanded': 'Extra-Expanded', 'ultra-expanded': 'Ultra-Expanded',
};

/** A Pango font description, as GTK apps take it: "Fira Code Light 14.25" */
function pangoFont(settings: Settings): string {
    // The width is a word in the description only when the family name does not select it
    const words = [weightNames(settings.weight).pango, hasWidthFamily(settings) ? '' : PANGO_WIDTHS[settings.fontWidth]];
    return [mainFamily(settings), ...words.filter(Boolean), toPoints(settings.size)].join(' ');
}


// Color helpers

function rgb(color: string): [number, number, number] {
    const hex = color.replace('#', '');
    return [0, 2, 4].map(i => parseInt(hex.substr(i, 2), 16)) as [number, number, number];
}

function toHex(r: number, g: number, b: number): string {
    return '#' + [r, g, b].map(x => Math.min(255, Math.max(0, Math.round(x))).toString(16).padStart(2, '0')).join('');
}

function adjustBrightness(color: string, amount: number): string {
    const [r, g, b] = rgb(color);
    return toHex(r + amount, g + amount, b + amount);
}

/** The color at fraction t on the way from color a to color b. */
function mix(a: string, b: string, t: number): string {
    const [ar, ag, ab] = rgb(a);
    const [br, bg, bb] = rgb(b);
    return toHex(ar + (br - ar) * t, ag + (bg - ag) * t, ab + (bb - ab) * t);
}

function isDark(color: string): boolean {
    const [r, g, b] = rgb(color);
    return (0.299 * r + 0.587 * g + 0.114 * b) < 128;
}

function toHsl(color: string): [number, number, number] {
    const [r, g, b] = rgb(color).map(x => x / 255);
    const max = Math.max(r, g, b);
    const min = Math.min(r, g, b);
    const l = (max + min) / 2;
    if (max === min) return [0, 0, l];
    const d = max - min;
    const s = d / (1 - Math.abs(2 * l - 1));
    let h: number;
    if (max === r) h = ((g - b) / d) % 6;
    else if (max === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    return [(h * 60 + 360) % 360, s, l];
}

function fromHsl(h: number, s: number, l: number): string {
    const c = (1 - Math.abs(2 * l - 1)) * s;
    const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
    const m = l - c / 2;
    const [r, g, b] = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x]
        : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
    return toHex((r + m) * 255, (g + m) * 255, (b + m) * 255);
}

// The 16 terminal colors, in ANSI order: black, red, green, yellow, blue, magenta,
// cyan, white, then the bright version of each. A program expects red to be red,
// so each slot takes the scheme color with the nearest hue. When the scheme has no
// color near a hue, the slot gets that hue at the scheme's typical saturation and lightness.
const ANSI_HUES = [0, 120, 60, 240, 300, 180]; // red, green, yellow, blue, magenta, cyan

function ansiPalette(settings: Settings): string[] {
    const scheme = settings.colorScheme;
    const dark = isDark(scheme.bg);
    // The foreground color is not a candidate: a hue slot must stand out from plain text
    const colors = TOKEN_KEYS.map(key => scheme[key]).filter(c => c !== scheme.fg && toHsl(c)[1] > 0.2);
    const typical = (index: 1 | 2, fallback: number) => {
        const values = colors.map(c => toHsl(c)[index]).sort((a, b) => a - b);
        return values.length ? values[Math.floor(values.length / 2)] : fallback;
    };
    // Kept in a range that stays readable on the background
    const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));
    const saturation = clamp(typical(1, 0.6), 0.4, 0.75);
    const lightness = dark ? clamp(typical(2, 0.65), 0.6, 0.72) : clamp(typical(2, 0.4), 0.3, 0.45);
    const hueDistance = (a: number, b: number) => Math.min(Math.abs(a - b), 360 - Math.abs(a - b));

    const normal = ANSI_HUES.map(hue => {
        const nearest = colors
            .map(c => ({ c, d: hueDistance(toHsl(c)[0], hue) }))
            .sort((a, b) => a.d - b.d)[0];
        return nearest && nearest.d <= 40 ? nearest.c : fromHsl(hue, saturation, lightness);
    });
    const step = dark ? 25 : -25;
    // Black and white are neutral, also when the scheme has a colored foreground
    const neutral = (color: string) => {
        const [h, sat, l] = toHsl(color);
        return fromHsl(h, Math.min(sat, 0.15), l);
    };
    const [dim, bright] = dark ? [neutral(scheme.bg), neutral(scheme.fg)] : [neutral(scheme.fg), neutral(scheme.bg)];
    const black = dark ? mix(dim, bright, 0.08) : dim;
    const white = dark ? bright : mix(bright, dim, 0.15);
    const brightBlack = mix(dim, bright, 0.45);
    const brightWhite = dark ? adjustBrightness(bright, 25) : bright;
    return [black, ...normal, white, brightBlack, ...normal.map(c => adjustBrightness(c, step)), brightWhite];
}

function selectionColor(settings: Settings): string {
    return mix(settings.colorScheme.bg, settings.colorScheme.fg, 0.25);
}

function schemeTitle(settings: Settings): string {
    return `Phoropter ${settings.colorScheme.name}`;
}

function escapeXml(text: string): string {
    return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}


// TextMate scopes, which VS Code and Sublime Text both use
const TEXTMATE_SCOPES: Record<TokenKey, string[]> = {
    comment: ['comment', 'punctuation.definition.comment'],
    string: ['string'],
    keyword: ['keyword', 'storage.type', 'storage.modifier'],
    function: ['entity.name.function', 'support.function', 'meta.function-call'],
    literal: ['constant.numeric', 'constant.language'],
    variable: ['variable'],
    type: ['entity.name.type', 'entity.name.class', 'support.type', 'support.class'],
    // After "keyword", so that it wins for operators
    operator: ['keyword.operator'],
};

function fontStyleWords(style: TokenStyle): string {
    return [style.bold && 'bold', style.italic && 'italic'].filter(Boolean).join(' ');
}

function vscodeConfig(settings: Settings): ConfigFile[] {
    const scheme = settings.colorScheme;
    const tokens = tokenStyles(settings);
    const name = primaryFontName(settings.font);
    const content = {
        'editor.fontFamily': cssFontList(settings, "'"),
        'editor.fontSize': settings.size,
        'editor.fontWeight': String(settings.weight),
        'editor.fontLigatures': !!findFont(name)?.ligatures,
        'editor.letterSpacing': settings.letterSpacing || 0,
        'editor.lineHeight': settings.lineHeight,
        'workbench.colorTheme': isDark(scheme.bg) ? 'Default Dark Modern' : 'Default Light Modern',
        'workbench.colorCustomizations': {
            'editor.background': scheme.bg,
            'editor.foreground': scheme.fg,
            'editor.selectionBackground': selectionColor(settings),
            'editorCursor.foreground': scheme.fg,
            'editorLineNumber.foreground': scheme.comment,
        },
        'editor.tokenColorCustomizations': {
            textMateRules: TOKEN_KEYS.map(key => ({
                scope: TEXTMATE_SCOPES[key],
                settings: { foreground: tokens[key].color, fontStyle: fontStyleWords(tokens[key]) },
            })),
        },
    };
    return [{ filename: 'settings.json', content: JSON.stringify(content, null, 4) }];
}

// Vim highlight groups. Keyword, Number and Boolean link to these by default.
const VIM_GROUPS: Record<TokenKey, string> = {
    comment: 'Comment', string: 'String', keyword: 'Statement', function: 'Function',
    literal: 'Constant', variable: 'Identifier', type: 'Type', operator: 'Operator',
};

function vimConfig(settings: Settings): ConfigFile[] {
    const scheme = settings.colorScheme;
    const tokens = tokenStyles(settings);
    const name = mainFamily(settings);
    // MacVim takes the PostScript name of the face, which also selects the weight
    const macName = postscriptName(settings) ?? name.replace(/\s+/g, '\\ ');
    const columnSpace = Math.round(settings.letterSpacing || 0);
    const gui = (style: TokenStyle) => fontStyleWords(style).replace(' ', ',') || 'NONE';
    const colors = `" Code Phoropter color scheme: ${scheme.name}
" Save as ~/.vim/colors/phoropter.vim (Neovim: ~/.config/nvim/colors/phoropter.vim)
hi clear
if exists('syntax_on')
  syntax reset
endif
set background=${isDark(scheme.bg) ? 'dark' : 'light'}
let g:colors_name = 'phoropter'

hi Normal guifg=${scheme.fg} guibg=${scheme.bg}
hi Visual guibg=${selectionColor(settings)}
hi LineNr guifg=${scheme.comment}
hi Cursor guifg=${scheme.bg} guibg=${scheme.fg}
${TOKEN_KEYS.map(key => `hi ${VIM_GROUPS[key]} guifg=${tokens[key].color} gui=${gui(tokens[key])} cterm=${gui(tokens[key])}`).join('\n')}
`;
    const weight = settings.weight !== 400 ? `:W${settings.weight}` : '';
    const vimrc = `" Code Phoropter settings. Add these lines to your vimrc.

" The font applies to GUI Vim only. In a terminal, the terminal sets the font.
if has('gui_running')
  if has('gui_win32')
    set guifont=${name.replace(/\s+/g, '_')}:h${toPoints(settings.size)}${weight}
  elseif has('gui_macvim')
    set guifont=${macName}:h${toPoints(settings.size, true)}${columnSpace ? `\n    set columnspace=${columnSpace}` : ''}
  else
    set guifont=${pangoFont(settings).replace(/\s+/g, '\\ ')}
  endif
  set linespace=${extraLinePixels(settings)}
endif

" The color scheme has 24-bit colors
if has('termguicolors')
  set termguicolors
endif
colorscheme phoropter
`;
    return [
        { filename: 'colors/phoropter.vim', content: colors },
        { filename: 'vimrc-snippet.vim', content: vimrc },
    ];
}

const EMACS_FACES: Record<TokenKey, string[]> = {
    comment: ['font-lock-comment-face', 'font-lock-comment-delimiter-face'],
    string: ['font-lock-string-face'],
    keyword: ['font-lock-keyword-face'],
    function: ['font-lock-function-name-face'],
    literal: ['font-lock-constant-face'],
    variable: ['font-lock-variable-name-face'],
    type: ['font-lock-type-face'],
    operator: [], // has a face only from Emacs 29, and only in tree-sitter modes
};

const EMACS_WIDTHS: Record<string, string> = {
    'ultra-condensed': 'ultra-condensed', 'extra-condensed': 'extra-condensed', 'condensed': 'condensed',
    'semi-condensed': 'semi-condensed', 'semi-expanded': 'semi-expanded', 'semi-wide': 'semi-expanded',
    'expanded': 'expanded', 'wide': 'expanded', 'extra-expanded': 'extra-expanded', 'ultra-expanded': 'ultra-expanded',
};

function emacsConfig(settings: Settings): ConfigFile[] {
    const scheme = settings.colorScheme;
    const tokens = tokenStyles(settings);
    // The width is an attribute only when the family name does not select it
    const width = hasWidthFamily(settings) ? undefined : EMACS_WIDTHS[settings.fontWidth];
    const faces = TOKEN_KEYS.flatMap(key => EMACS_FACES[key].map(face => {
        const style = tokens[key];
        // A role weight is exact. Without one, a bold token is bold and the rest follow the main weight.
        const weight = weightNames(style.weight ?? (style.bold ? 700 : settings.weight)).emacs;
        const family = style.font ? ` :family "${style.font}"` : '';
        return `(set-face-attribute '${face} nil :foreground "${style.color}"${family} :weight '${weight} :slant '${style.italic ? 'italic' : 'normal'})`;
    }));
    const content = `;;; phoropter.el --- Code Phoropter settings (${scheme.name})
;; Add these lines to your init file, or save this file and add
;;   (load "~/.emacs.d/phoropter.el")

;; :height is in 1/10 point. On macOS a point is a pixel. Elsewhere it is 4/3 pixel.
(set-face-attribute 'default nil
                    :family "${mainFamily(settings)}"
                    :height (if (eq system-type 'darwin) ${Math.round(settings.size * 10)} ${Math.round(toPoints(settings.size) * 10)})
                    :weight '${weightNames(settings.weight).emacs}${width ? `\n                    :width '${width}` : ''}
                    :foreground "${scheme.fg}"
                    :background "${scheme.bg}")

;; Extra pixels between lines
(setq-default line-spacing ${extraLinePixels(settings)})

(set-face-attribute 'cursor nil :background "${scheme.fg}")
(set-face-attribute 'region nil :background "${selectionColor(settings)}")
${faces.join('\n')}
`;
    return [{ filename: 'phoropter.el', content }];
}

function windowsTerminalConfig(settings: Settings): ConfigFile[] {
    const scheme = settings.colorScheme;
    const ansi = ansiPalette(settings);
    const names = ['black', 'red', 'green', 'yellow', 'blue', 'purple', 'cyan', 'white'];
    const palette: Record<string, string> = {};
    names.forEach((n, i) => {
        palette[n] = ansi[i];
        palette['bright' + n[0].toUpperCase() + n.slice(1)] = ansi[i + 8];
    });
    const content = {
        profiles: {
            defaults: {
                font: {
                    face: mainFamily(settings),
                    size: toPoints(settings.size),
                    weight: weightNames(settings.weight).terminal,
                    cellHeight: String(settings.lineHeight),
                    // The letter spacing: the cell width in units of the character width
                    ...(settings.letterSpacing ? { cellWidth: `${cellWidthScale(settings)}ch` } : {}),
                },
                colorScheme: schemeTitle(settings),
            },
        },
        schemes: [{
            name: schemeTitle(settings),
            foreground: scheme.fg,
            background: scheme.bg,
            cursorColor: scheme.fg,
            selectionBackground: selectionColor(settings),
            ...palette,
        }],
    };
    return [{ filename: 'windows-terminal-settings.json', content: JSON.stringify(content, null, 4) }];
}

function puttyConfig(settings: Settings): ConfigFile[] {
    const scheme = settings.colorScheme;
    const ansi = ansiPalette(settings);
    // PuTTY has 22 colors: 0-5 are foreground, bold foreground, background, bold background,
    // cursor text and cursor. Then each ANSI color is followed by its bright version.
    const colours = [scheme.fg, ansi[15], scheme.bg, scheme.bg, scheme.bg, scheme.fg];
    for (let i = 0; i < 8; i++) colours.push(ansi[i], ansi[i + 8]);
    const lines = [
        'Windows Registry Editor Version 5.00',
        '',
        '[HKEY_CURRENT_USER\\Software\\SimonTatham\\PuTTY\\Sessions\\Default%20Settings]',
        `"Font"="${mainFamily(settings)}"`,
        `"FontHeight"=dword:${Math.round(toPoints(settings.size)).toString(16).padStart(8, '0')}`,
        `"FontIsBold"=dword:${settings.weight >= 600 ? '00000001' : '00000000'}`,
        ...colours.map((c, i) => `"Colour${i}"="${rgb(c).join(',')}"`),
        '',
    ];
    return [{ filename: 'putty-config.reg', content: lines.join('\r\n') }];
}

function sublimeConfig(settings: Settings): ConfigFile[] {
    const scheme = settings.colorScheme;
    const tokens = tokenStyles(settings);
    const padding = Math.round(extraLinePixels(settings) / 2);
    const preferences = {
        font_face: mainFamily(settings),
        font_size: toPoints(settings.size, IS_MAC),
        line_padding_top: padding,
        line_padding_bottom: padding,
        color_scheme: 'Packages/User/Phoropter.sublime-color-scheme',
    };
    const colorScheme = {
        name: schemeTitle(settings),
        author: 'Code Phoropter',
        globals: {
            background: scheme.bg,
            foreground: scheme.fg,
            caret: scheme.fg,
            selection: selectionColor(settings),
            line_highlight: mix(scheme.bg, scheme.fg, 0.07),
        },
        rules: TOKEN_KEYS.map(key => ({
            name: key,
            scope: TEXTMATE_SCOPES[key].join(', '),
            foreground: tokens[key].color,
            font_style: fontStyleWords(tokens[key]),
        })),
    };
    return [
        { filename: 'Phoropter.sublime-color-scheme', content: JSON.stringify(colorScheme, null, 4) },
        { filename: 'Preferences.sublime-settings', content: JSON.stringify(preferences, null, 4) },
    ];
}

const ATOM_SELECTORS: Record<TokenKey, string> = {
    comment: '.syntax--comment',
    string: '.syntax--string',
    keyword: '.syntax--keyword, .syntax--storage',
    function: '.syntax--entity.syntax--name.syntax--function, .syntax--support.syntax--function',
    literal: '.syntax--constant.syntax--numeric, .syntax--constant.syntax--language',
    variable: '.syntax--variable',
    type: '.syntax--entity.syntax--name.syntax--type, .syntax--support.syntax--class',
    operator: '.syntax--keyword.syntax--operator',
};

function atomConfig(settings: Settings): ConfigFile[] {
    const scheme = settings.colorScheme;
    const tokens = tokenStyles(settings);
    const rules = TOKEN_KEYS.map(key => {
        const style = tokens[key];
        const lines = [`color: ${style.color} !important;`];
        if (style.font) lines.push(`font-family: "${style.font}", monospace !important;`);
        if (style.weight || style.bold) lines.push(`font-weight: ${style.weight ?? 700} !important;`);
        if (style.italic) lines.push('font-style: italic !important;');
        return `  ${ATOM_SELECTORS[key]} {\n${lines.map(l => `    ${l}`).join('\n')}\n  }`;
    });
    const content = `atom-text-editor {
  font-family: ${cssFontList(settings, '"')} !important;
  font-size: ${settings.size}px !important;
  font-weight: ${settings.weight} !important;
  font-stretch: ${settings.fontWidth || 'normal'} !important;
  letter-spacing: ${settings.letterSpacing || 0}px !important;
  line-height: ${settings.lineHeight} !important;
}

atom-text-editor.editor {
  background-color: ${scheme.bg} !important;
  color: ${scheme.fg} !important;

${rules.join('\n\n')}
}
`;
    return [{ filename: 'styles.less', content }];
}

// The language-independent attribute keys of a JetBrains color scheme
const JETBRAINS_KEYS: Record<TokenKey, string[]> = {
    comment: ['DEFAULT_LINE_COMMENT', 'DEFAULT_BLOCK_COMMENT', 'DEFAULT_DOC_COMMENT'],
    string: ['DEFAULT_STRING'],
    keyword: ['DEFAULT_KEYWORD'],
    function: ['DEFAULT_FUNCTION_DECLARATION', 'DEFAULT_FUNCTION_CALL'],
    literal: ['DEFAULT_NUMBER', 'DEFAULT_CONSTANT'],
    variable: ['DEFAULT_IDENTIFIER', 'DEFAULT_LOCAL_VARIABLE', 'DEFAULT_PARAMETER'],
    type: ['DEFAULT_CLASS_NAME', 'DEFAULT_CLASS_REFERENCE', 'DEFAULT_INTERFACE_NAME'],
    operator: ['DEFAULT_OPERATION_SIGN'],
};

function intellijConfig(settings: Settings): ConfigFile[] {
    const scheme = settings.colorScheme;
    const tokens = tokenStyles(settings);
    const name = primaryFontName(settings.font);
    const hex = (color: string) => color.replace('#', '');
    const attributes = TOKEN_KEYS.flatMap(key => JETBRAINS_KEYS[key].map(attribute => {
        const style = tokens[key];
        // FONT_TYPE: 1 is bold, 2 is italic, 3 is both
        const fontType = (style.bold ? 1 : 0) + (style.italic ? 2 : 0);
        return `    <option name="${attribute}">
      <value>
        <option name="FOREGROUND" value="${hex(style.color)}" />${fontType ? `\n        <option name="FONT_TYPE" value="${fontType}" />` : ''}
      </value>
    </option>`;
    }));
    const content = `<scheme name="${escapeXml(schemeTitle(settings))}" version="142" parent_scheme="${isDark(scheme.bg) ? 'Darcula' : 'Default'}">
  <option name="LINE_SPACING" value="${lineHeightScale(settings)}" />
  <option name="EDITOR_FONT_SIZE" value="${settings.size}" />
  <option name="EDITOR_FONT_NAME" value="${escapeXml(mainFamily(settings))}" />
  <option name="EDITOR_LIGATURES" value="${!!findFont(name)?.ligatures}" />
  <colors>
    <option name="CARET_COLOR" value="${hex(scheme.fg)}" />
    <option name="CARET_ROW_COLOR" value="${hex(mix(scheme.bg, scheme.fg, 0.07))}" />
    <option name="CONSOLE_BACKGROUND_KEY" value="${hex(scheme.bg)}" />
    <option name="GUTTER_BACKGROUND" value="${hex(scheme.bg)}" />
    <option name="INDENT_GUIDE" value="${hex(mix(scheme.bg, scheme.fg, 0.15))}" />
    <option name="LINE_NUMBERS_COLOR" value="${hex(scheme.comment)}" />
    <option name="SELECTION_BACKGROUND" value="${hex(selectionColor(settings))}" />
  </colors>
  <attributes>
    <option name="TEXT">
      <value>
        <option name="FOREGROUND" value="${hex(scheme.fg)}" />
        <option name="BACKGROUND" value="${hex(scheme.bg)}" />
      </value>
    </option>
${attributes.join('\n')}
  </attributes>
</scheme>
`;
    return [{ filename: 'phoropter.icls', content }];
}

// A fixed id: a new download replaces the profile of the previous download
const ITERM_PROFILE_GUID = '6F1A2B7C-3D4E-4F50-9A6B-C0DE0F0A0B0C';

// A dynamic profile: a JSON file that iTerm2 loads from its DynamicProfiles directory.
// It holds the font and the spacing, which a color preset file cannot.
function itermConfig(settings: Settings): ConfigFile[] {
    const scheme = settings.colorScheme;
    const name = primaryFontName(settings.font);
    const color = (hex: string) => {
        const [r, g, b] = rgb(hex).map(x => Number((x / 255).toFixed(6)));
        return { 'Color Space': 'sRGB', 'Red Component': r, 'Green Component': g, 'Blue Component': b, 'Alpha Component': 1 };
    };
    const colors: Record<string, ReturnType<typeof color>> = {};
    ansiPalette(settings).forEach((hex, i) => { colors[`Ansi ${i} Color`] = color(hex); });
    const clamp = (value: number) => Number(Math.min(2, Math.max(0.5, value)).toFixed(3));
    const profile = {
        Name: 'Code Phoropter',
        Guid: ITERM_PROFILE_GUID,
        // The PostScript name of the face, then the size in points
        'Normal Font': `${postscriptName(settings) ?? guessedPostscriptName(settings)} ${settings.size}`,
        'Use Non-ASCII Font': false,
        'ASCII Ligatures': !!findFont(name)?.ligatures,
        'Use Bold Font': true,
        'Use Italic Font': true,
        'Horizontal Spacing': clamp(cellWidthScale(settings)),
        'Vertical Spacing': clamp(settings.lineHeight / NATURAL_LINE_HEIGHT),
        ...colors,
        'Background Color': color(scheme.bg),
        'Foreground Color': color(scheme.fg),
        'Bold Color': color(scheme.fg),
        'Cursor Color': color(scheme.fg),
        'Cursor Text Color': color(scheme.bg),
        'Selection Color': color(selectionColor(settings)),
        'Selected Text Color': color(scheme.fg),
    };
    return [{ filename: 'phoropter-iterm2.json', content: JSON.stringify({ Profiles: [profile] }, null, 2) }];
}

// The profile that GNOME Terminal uses when the profile list is empty
const GNOME_DEFAULT_PROFILE = 'b1dcc9dd-5262-4d8d-a863-c897e6d979b9';

function gnomeTerminalConfig(settings: Settings): ConfigFile[] {
    const scheme = settings.colorScheme;
    const palette = ansiPalette(settings).map(c => `'${c}'`).join(', ');
    const content = `#!/bin/sh
# Adds a GNOME Terminal profile named "Code Phoropter".
# Run: sh gnome-terminal-phoropter.sh
set -e

id=$(uuidgen)
base=/org/gnome/terminal/legacy/profiles:

dconf load "$base/:$id/" <<'EOF'
[/]
visible-name='Code Phoropter'
font='${pangoFont(settings)}'
use-system-font=false
use-theme-colors=false
background-color='${scheme.bg}'
foreground-color='${scheme.fg}'
palette=[${palette}]
bold-color-same-as-fg=true
cursor-colors-set=true
cursor-background-color='${scheme.fg}'
cursor-foreground-color='${scheme.bg}'
cell-height-scale=${lineHeightScale(settings)}${settings.letterSpacing > 0 ? `\ncell-width-scale=${Math.min(2, cellWidthScale(settings))}` : ''}
EOF

# A profile shows in the terminal only when its id is in the profile list
list=$(dconf read "$base/list")
case "$list" in
    ''|'@as []'|'[]') list="['${GNOME_DEFAULT_PROFILE}', '$id']" ;;
    *) list="\${list%]}, '$id']" ;;
esac
dconf write "$base/list" "$list"

echo "Added the profile 'Code Phoropter'. Select it in the terminal menu under Profiles."
`;
    return [{ filename: 'gnome-terminal-phoropter.sh', content }];
}

const configTemplates: Record<string, (settings: Settings) => ConfigFile[]> = {
    vscode: vscodeConfig,
    vim: vimConfig,
    emacs: emacsConfig,
    windowsTerminal: windowsTerminalConfig,
    putty: puttyConfig,
    sublimeText: sublimeConfig,
    atom: atomConfig,
    intellij: intellijConfig,
    iterm2: itermConfig,
    gnomeTerminal: gnomeTerminalConfig,
};


// Installation instructions for each editor
const installationInstructions: Record<string, { title: string; steps: string[] }> = {
    vscode: {
        title: 'VS Code Installation',
        steps: [
            'Open VS Code',
            'Press <code>Ctrl+Shift+P</code> (or <code>Cmd+Shift+P</code> on Mac)',
            'Type "Preferences: Open User Settings (JSON)"',
            'Copy the entries of the downloaded <code>settings.json</code> into your own <code>settings.json</code>',
            'Save the file. The font and the colors change immediately',
            'To go back to the colors of your theme, remove the two <code>Customizations</code> entries'
        ]
    },
    vim: {
        title: 'Vim Installation',
        steps: [
            'Unpack the downloaded ZIP file',
            'Copy <code>colors/phoropter.vim</code> to <code>~/.vim/colors/</code> (Neovim: <code>~/.config/nvim/colors/</code>)',
            'Add the lines of <code>vimrc-snippet.vim</code> to your <code>~/.vimrc</code>',
            'Restart Vim',
            'The font applies to GUI Vim only. In a terminal, the terminal sets the font'
        ]
    },
    emacs: {
        title: 'Emacs Installation',
        steps: [
            'Save the downloaded <code>phoropter.el</code> in <code>~/.emacs.d/</code>',
            'Add <code>(load "~/.emacs.d/phoropter.el")</code> to your init file, after any <code>load-theme</code> call',
            'Restart Emacs, or open the file and run <code>M-x eval-buffer</code>'
        ]
    },
    windowsTerminal: {
        title: 'Windows Terminal Installation',
        steps: [
            'Open Windows Terminal',
            'Press <code>Ctrl+,</code> to open settings',
            'Click "Open JSON file" at the bottom left',
            'Copy the <code>font</code> and <code>colorScheme</code> entries into <code>profiles.defaults</code>',
            'Add the scheme to the <code>schemes</code> list',
            'Save the file. The changes apply immediately'
        ]
    },
    iterm2: {
        title: 'iTerm2 Installation',
        steps: [
            'Copy the downloaded <code>phoropter-iterm2.json</code> to <code>~/Library/Application Support/iTerm2/DynamicProfiles/</code>',
            'iTerm2 loads the file immediately. The profile has the name "Code Phoropter"',
            'Open a window with it from the <strong>Profiles</strong> menu',
            'To make it the default, go to <strong>Settings</strong> → <strong>Profiles</strong>, select the profile and choose <strong>Other Actions...</strong> → <strong>Set as Default</strong>',
            'The profile sets the font, the spacing and the colors'
        ]
    },
    gnomeTerminal: {
        title: 'GNOME Terminal Installation',
        steps: [
            'Open a terminal in the download directory',
            'Run <code>sh gnome-terminal-phoropter.sh</code>',
            'The script adds a profile with the name "Code Phoropter"',
            'Select the profile in the terminal menu under <strong>Profiles</strong>',
            'To make it the default, open <strong>Preferences</strong> and choose <strong>Set as default</strong> for the profile'
        ]
    },
    putty: {
        title: 'PuTTY Installation',
        steps: [
            'Double-click the downloaded <code>.reg</code> file',
            'Click "Yes" to confirm the registry change',
            'Open PuTTY. The font and the colors are in "Default Settings"',
            'New sessions use them. Saved sessions keep their own settings'
        ]
    },
    sublimeText: {
        title: 'Sublime Text Installation',
        steps: [
            'Unpack the downloaded ZIP file',
            'In Sublime Text, choose <strong>Preferences</strong> → <strong>Browse Packages...</strong> and open the <code>User</code> directory',
            'Copy <code>Phoropter.sublime-color-scheme</code> into that directory',
            'Choose <strong>Preferences</strong> → <strong>Settings</strong>',
            'Copy the entries of <code>Preferences.sublime-settings</code> into your user settings and save'
        ]
    },
    atom: {
        title: 'Atom / Pulsar Installation',
        steps: [
            'Choose <strong>Edit</strong> → <strong>Stylesheet...</strong> (on Mac: <strong>Atom</strong> → <strong>Stylesheet...</strong>)',
            'This opens your <code>styles.less</code> file',
            'Add the content of the downloaded <code>styles.less</code> at the end',
            'Save the file. The changes apply immediately'
        ]
    },
    intellij: {
        title: 'IntelliJ/JetBrains Installation',
        steps: [
            'Go to <strong>File</strong> → <strong>Settings</strong> → <strong>Editor</strong> → <strong>Color Scheme</strong>',
            'Click the gear icon → <strong>Import Scheme...</strong>',
            'Select the downloaded <code>.icls</code> file',
            'Apply. The scheme sets the colors and the font',
            'If the font does not change, open <strong>Color Scheme</strong> → <strong>Color Scheme Font</strong> and select "Use color scheme font instead of the default"'
        ]
    }
};


// The apps that have no setting for letter spacing
const NO_LETTER_SPACING: Record<string, string> = {
    emacs: 'Emacs has',
    putty: 'PuTTY has',
    sublimeText: 'Sublime Text has',
    intellij: 'JetBrains IDEs have',
};

/** A warning for the instructions when the export cannot apply all of the settings. */
function exportWarning(editor: string, settings: Settings): string | undefined {
    const spacing = settings.letterSpacing || 0;
    if (spacing) {
        if (NO_LETTER_SPACING[editor]) {
            return `${NO_LETTER_SPACING[editor]} no setting for letter spacing. Your letter spacing of ${spacing}px is not in the export.`;
        }
        if (editor === 'vim') {
            const columnSpace = Math.round(spacing);
            return `Only MacVim has a setting for letter spacing (<code>columnspace</code>), and it takes whole pixels. `
                + (columnSpace
                    ? `The export sets it to ${columnSpace} for MacVim. Other versions of Vim show the font without your letter spacing of ${spacing}px.`
                    : `Your letter spacing of ${spacing}px rounds to 0, so it is not in the export.`);
        }
        if (editor === 'gnomeTerminal' && spacing < 0) {
            return `GNOME Terminal can only make the letter spacing wider. Your letter spacing of ${spacing}px is not in the export.`;
        }
    }
    if (editor === 'iterm2' && !postscriptName(settings)) {
        return `iTerm2 identifies a font by its PostScript name, and we do not know that name for ${primaryFontName(settings.font)}. `
            + `The export has a guess (<code>${guessedPostscriptName(settings)}</code>). If the profile shows another font, select the font on the <strong>Text</strong> tab of the profile.`;
    }
    return undefined;
}

function saveBlob(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

// Download the configuration for one editor. An editor that needs several files gets a ZIP file.
export async function downloadConfig(editor: string): Promise<void> {
    const template = configTemplates[editor];
    if (!template) return;

    fontNames = (await import('../../font-names.json')).default as Record<string, FontNames>;
    const settings = currentSettings();
    const files = template(settings);
    if (files.length === 1) {
        saveBlob(new Blob([files[0].content], { type: 'text/plain' }), files[0].filename);
    } else {
        const { default: JSZip } = await import('jszip');
        const zip = new JSZip();
        files.forEach(file => zip.file(file.filename, file.content));
        saveBlob(await zip.generateAsync({ type: 'blob' }), `phoropter-${editor.toLowerCase()}.zip`);
    }

    // Show installation instructions after download
    showInstallationInstructions(editor, exportWarning(editor, settings));
}


function showInstallationInstructions(editor: string, warning?: string): void {
    const instructions = installationInstructions[editor];
    if (!instructions) return;
    
    // Create modal overlay
    const modal = document.createElement('div');
    modal.className = 'instruction-modal';
    modal.innerHTML = `
        <div class="instruction-content">
            <div class="instruction-header">
                <h3>${instructions.title}</h3>
                <button class="close-btn" data-action="closeModal">×</button>
            </div>
            <div class="instruction-body">
                ${warning ? `<p class="instruction-warning">${warning}</p>` : ''}
                <ol>
                    ${instructions.steps.map(step => `<li>${step}</li>`).join('')}
                </ol>
            </div>
            <div class="instruction-footer">
                <button data-action="closeModal">Got it!</button>
            </div>
        </div>
    `;
    
    document.body.appendChild(modal);
}
