import type { Settings } from '../types';
import { currentSettings } from './settings';
import { getFontDownloadInfo, type FontDownloadInfo } from '../fonts/similarity';
import { getRoleLabel, roleToHLJS } from '../roles';
import { state } from '../state';

// Generate README.txt content
function generateReadme(fontName: string, fontInfo: FontDownloadInfo, results: Settings): string {
    // Optional roles block for multi-font mode
    let rolesBlock = '';
    if (Object.keys(results.roles).length) {
        const lines = Object.keys(roleToHLJS)
            .filter(r => results.roles[r])
            .map(r => {
                const { font, weight, style } = results.roles[r];
                return `${getRoleLabel(r)}: ${font}, ${weight}${style !== 'normal' ? `, ${style}` : ''}`;
            });
        if (lines.length) {
            rolesBlock = `\n----- Roles ----\n${lines.join('\n')}`;
        }
    }
    return `Code Phoropter - Font Configuration Package
============================================

Font: ${fontName}
Generated: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}

INSTALLATION INSTRUCTIONS
========================

1. INSTALL THE FONT
   ${fontInfo.type === 'system' ? 
     `This is a system font that should already be installed on your system.
   If not available, ${fontInfo.instructions}` :
     `This is a free font. Extract the font files from this package and:
   
   Windows:
   - Right-click on the .ttf/.otf files and select "Install"
   - Or copy files to C:\\Windows\\Fonts\\
   
   macOS:
   - Double-click the .ttf/.otf files and click "Install Font"
   - Or copy files to ~/Library/Fonts/ (user) or /Library/Fonts/ (system)
   
   Linux:
   - Copy files to ~/.fonts/ (user) or /usr/share/fonts/ (system)
   - Run: fc-cache -f -v`}

2. APPLY THE SETTINGS
   Use the settings from config.css in your code editor:
   
   Font Family: ${results.font}
   Font Size: ${results.size}px
   Font Weight: ${results.weight}
   Line Height: ${results.lineHeight}
   Background: ${results.colorScheme.bg}
   Text Color: ${results.colorScheme.fg}${rolesBlock}

3. EDITOR CONFIGURATION
   
   VS Code:
   Add to settings.json:
   {
     "editor.fontFamily": ${results.font},
     "editor.fontSize": ${results.size},
     "editor.fontWeight": "${results.weight}",
     "editor.lineHeight": ${results.lineHeight}
   }
   
   Sublime Text:
   Add to Preferences > Settings:
   {
     "font_face": "${fontName}",
     "font_size": ${results.size},
     "line_padding_top": 1,
     "line_padding_bottom": 1
   }
   
   Vim/NeoVim:
   Add to .vimrc:
   set guifont=${fontName}:h${results.size}
   
   Terminal:
   Configure your terminal to use "${fontName}" at ${results.size}pt

TROUBLESHOOTING
==============

If the font doesn't appear in your editor:
1. Restart your editor after installing the font
2. Check that the font name matches exactly (case-sensitive)
3. Verify the font is properly installed system-wide
4. Some editors require the exact PostScript name of the font

For support, visit: https://github.com/your-repo/code-phoropter

Happy coding with your optimized font settings!
`;
}


// Download font package with configuration
export async function downloadFontPackage(): Promise<void> {
    const results = currentSettings();
    const fontName = results.font.replace(/["']/g, '').split(',')[0].trim();
    const fontInfo = getFontDownloadInfo(fontName);
    
    // Create ZIP file
    const { default: JSZip } = await import('jszip');
    const zip = new JSZip();
    
    // Add configuration file
    let css = `/* Your optimized code display settings */
/* Generated by Code Phoropter on ${new Date().toLocaleDateString()} */

font-family: ${results.font};
font-size: ${results.size}px;
font-weight: ${results.weight};
line-height: ${results.lineHeight};
background-color: ${results.colorScheme.bg};
color: ${results.colorScheme.fg};

/* Syntax highlighting colors */
.keyword { color: ${results.colorScheme.keyword}; }
.string { color: ${results.colorScheme.string}; }
.comment { color: ${results.colorScheme.comment}; }
.function { color: ${results.colorScheme.function}; }

/* Multi-Font Roles (optional) */
/* Uncomment and adjust if using multiple fonts per syntax role */`;

    if (state.currentRoleCss) {
        css += `\n${state.currentRoleCss}`;
    }

    css += `

/* VS Code settings.json snippet */
/*
{
  "editor.fontFamily": ${results.font},
  "editor.fontSize": ${results.size},
  "editor.fontWeight": "${results.weight}",
  "editor.lineHeight": ${results.lineHeight},
  "workbench.colorTheme": "your-preferred-theme"
}
*/`;
    
    zip.file('config.css', css);
    
    // Add README
    const readme = generateReadme(fontName, fontInfo, results);
    zip.file('README.txt', readme);
    
    // Add settings data for import
    const exportData = {
        settings: results,
        css: css,
        timestamp: new Date().toISOString(),
        version: '1.0',
        multiFont: !!state.currentRoleCss,
        roles: {
            mapping: state.currentRoleMapping
        },
        fontInfo: {
            name: fontName,
            downloadUrl: fontInfo.downloadUrl || null,
            instructions: fontInfo.instructions,
            type: fontInfo.type || 'unknown'
        }
    };
    zip.file('settings.json', JSON.stringify(exportData, null, 2));
    
    // Try to download font files if available and free
    if (fontInfo.type === 'free' && fontInfo.downloadUrl) {
            // For Google Fonts, we can't directly download, so add instructions
            if (fontInfo.downloadUrl.includes('fonts.google.com/download')) {
                zip.file('FONT_DOWNLOAD.txt', 
                    `Font Download Instructions for ${fontName}
====================================

This package includes your configuration but not the font files themselves.
To get the font files:

1. Visit: ${fontInfo.downloadUrl}
2. Click "Download family" to get a ZIP file
3. Extract the font files (.ttf) from the downloaded ZIP
4. Install the fonts on your system (see README.txt)

The font files should be placed in this same folder if you want 
a complete package for distribution.

Note: Due to browser security restrictions, font files cannot be 
automatically downloaded from Google Fonts.`);
            } else {
                // For other free fonts with direct download links, add placeholder
                zip.file('FONT_DOWNLOAD.txt', 
                    `Font files not included - Download separately from:
${fontInfo.downloadUrl}

Extract font files to this folder after downloading.`);
            }
    } else if (fontInfo.type === 'system') {
        zip.file('SYSTEM_FONT.txt', 
            `This is a system font: ${fontName}
===============================

This font should already be installed on your system.
No additional download required.

If the font is missing: ${fontInfo.instructions}

Use the config.css settings in this package.`);
    }
    
    // Generate and download ZIP
    try {
        const content = await zip.generateAsync({type: 'blob'});
        const url = URL.createObjectURL(content);
        const a = document.createElement('a');
        a.href = url;
        a.download = `code-phoropter-${fontName.replace(/\s+/g, '-').toLowerCase()}-config.zip`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        
        alert(`Font package downloaded! Contains configuration files and installation instructions for ${fontName}.`);
    } catch (error) {
        console.error('Error creating ZIP file:', error);
        alert('Failed to create download package. Please try copying the settings instead.');
    }
}
